name: Release

on:
    pull_request:
        branches:
            - master
        types: [closed]

jobs:
    release:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.ADMIN_TOKEN }}

            - name: Pulls all tags & commits (needed for lerna / semantic release to correctly version)
              run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*

            - name: Configure CI Git User
              run: |
                  git config --global user.name 'gmukul01'
                  git config --global user.email 'mukulbansal01@gmail.com'

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'

            - name: Install dependencies
              run: yarn

            - name: Linting
              run: yarn lint

            - name: Publish packages
              run: yarn release
              env:
                  GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Deploy storybook
              run: yarn storybook:deploy -- --ci
              env:
                  GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
